// export { default as ContactsForm } from './Contacts/ContactsForm/ContactsForm';
export { default as HerosList } from './Heros/HerosList/HerosList';
export { default as HerosDetailsList } from './Heros/HerosDetailsList/HerosDetailsList';
export { default as Header } from './Header/Header';
export { default as Footer } from './Footer/Footer';
// export { default as Footer } from './Footer/Footer';
// export { default as RegisterForm } from './Register/RegisterForm';
// export { default as LoginForm } from './Login/LoginForm';
// export { default as HeaderMenu } from './Header/HeaderMenu/HeaderMenu';
// export { default as HeaderAuth } from './Header/HeaderAuth/HeaderAuth';
// export { default as UserMenu } from './Header/UserMenu/UserMenu';
